# Generated by Django 2.2.3 on 2019-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
