# Generated by Django 2.2.3 on 2019-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000000000000', max_length=20, unique=True),
        ),
    ]
